// ...existing code...
#ifndef JS_NET_MODULE_H
#define JS_NET_MODULE_H
#include "quickjs.h"

// ...existing code...
JSModuleDef *js_init_module_net(JSContext *ctx, const char *module_name);
// ...existing code...
#endif
